seq1:
  - [AffA, AffB]
  - [AutA, PerB]
  - [PerA, AutB]
  - [PhyA, PhyB]
  - [AutA, AutB]
  - [PerB, PhyB]
  - [PhyA, AffA]
  - [AffB, PerA]
  - [PerB, AffA]
  - [PhyB, PerA]
  - [AffB, AutA]
  - [AutB, PhyA]
  - [PhyB, AutA]
  - [AffA, PhyA]
  - [AutB, AffB]
  - [PerA, PerB]

seq2:
  - [AutA, AutB]
  - [PerA, PhyA]
  - [PhyB, AffA]
  - [AffB, PerB]
  - [PerA, AffA]
  - [PhyA, PerB]
  - [AffB, AutA]
  - [AutB, PhyB]
  - [PhyA, AutA]
  - [AffA, PhyB]
  - [AutB, AffB]
  - [PerB, PerA]
  - [AffA, AffB]
  - [AutA, PerA]
  - [PerB, AutB]
  - [PhyB, PhyA]
